import os
from pathlib import Path
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, 
    HRFlowable, KeepTogether, ListFlowable, ListItem
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from config import settings

# ── Color Palette (Warm Editorial - matching reference notes) ──
CREAM_BG     = colors.HexColor('#FAF7F2')
CARD_BG      = colors.HexColor('#FFFFFF')
SECTION_BG   = colors.HexColor('#F5F0E8')
BORDER_WARM  = colors.HexColor('#E5DDD0')
BORDER_STRONG= colors.HexColor('#C8BCA8')
TEXT_PRIMARY  = colors.HexColor('#2C2316')
TEXT_SECONDARY= colors.HexColor('#5C4F3A')
TEXT_MUTED   = colors.HexColor('#8A7E6B')
ACCENT_OLIVE = colors.HexColor('#7B8C3E')
ACCENT_BROWN = colors.HexColor('#8B6F47')
ACCENT_BROWN_LT = colors.HexColor('#C9A96E')
ACCENT_TERRACOTTA = colors.HexColor('#C17F59')
ACCENT_SAGE  = colors.HexColor('#9CAF88')
CTA_GREEN    = colors.HexColor('#B8D44A')


class IExporterService:
    """Service interface for exporting notes, quizzes, study guides into PDF, Markdown, and Anki formats."""

    @classmethod
    def export_markdown(cls, title: str, structured_content: Dict[str, Any], include_quiz: bool = True) -> str:
        """Generates clean Markdown representation of the lecture notes and study guide."""
        md = []
        md.append(f"# {title}\n")
        md.append(f"*Generated by Clipnote AI Lecture Note Taker*\n\n")

        # Study Guide
        if structured_content.get("study_guide"):
            md.append("## 📌 Executive Study Guide\n")
            md.append(f"{structured_content['study_guide']}\n\n")

        # Notes
        notes = structured_content.get("notes", [])
        if notes:
            md.append("## 📝 Sectioned Notes\n")
            for item in notes:
                ts = item.get("timestamp_reference", 0.0)
                minutes = int(ts // 60)
                seconds = int(ts % 60)
                ts_str = f"{minutes:02d}:{seconds:02d}"
                md.append(f"### {item.get('section_title', 'Section')} `[{ts_str}]`\n")
                md.append(f"{item.get('content', '')}\n\n")

        # Key Concepts
        concepts = structured_content.get("key_concepts", [])
        if concepts:
            md.append("## 💡 Key Concepts & Glossary\n")
            for concept in concepts:
                term = concept.get("term", "")
                definition = concept.get("definition", "")
                md.append(f"- **{term}**: {definition}\n")
            md.append("\n")

        # Quiz
        if include_quiz:
            quiz = structured_content.get("quiz", [])
            if quiz:
                md.append("## 🧠 Self-Assessment Quiz\n")
                for i, q in enumerate(quiz, 1):
                    md.append(f"#### Question {i}: {q.get('question', '')}\n")
                    if q.get("type") == "mcq" and q.get("options"):
                        for opt in q["options"]:
                            md.append(f"- [ ] {opt}\n")
                    md.append(f"\n> **Answer**: {q.get('correct_answer', '')}\n")
                    if q.get("explanation"):
                        md.append(f"> *Explanation*: {q['explanation']}\n")
                    md.append("\n")

        return "".join(md)

    @classmethod
    def export_pdf(cls, title: str, structured_content: Dict[str, Any], output_path: Path) -> Path:
        """Generates a beautifully styled editorial PDF matching the warm reference note design."""
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=letter,
            rightMargin=48, leftMargin=48, topMargin=48, bottomMargin=48
        )
        styles = getSampleStyleSheet()

        # ── Custom Styles ──
        title_style = ParagraphStyle(
            'WarmTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=26,
            leading=32,
            textColor=TEXT_PRIMARY,
            spaceAfter=4,
            alignment=TA_LEFT
        )

        subtitle_style = ParagraphStyle(
            'WarmSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=10,
            textColor=TEXT_MUTED,
            spaceAfter=20,
            alignment=TA_LEFT
        )

        section_header_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=TEXT_PRIMARY,
            spaceBefore=18,
            spaceAfter=8,
            borderWidth=0,
        )

        subsection_style = ParagraphStyle(
            'SubsectionTitle',
            parent=styles['Heading3'],
            fontName='Helvetica-Bold',
            fontSize=11,
            leading=14,
            textColor=ACCENT_BROWN,
            spaceBefore=10,
            spaceAfter=4,
        )

        body_style = ParagraphStyle(
            'WarmBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=15,
            textColor=TEXT_SECONDARY,
            spaceAfter=8,
        )

        bullet_style = ParagraphStyle(
            'WarmBullet',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=TEXT_SECONDARY,
            leftIndent=16,
            spaceAfter=4,
            bulletIndent=0,
        )

        timestamp_style = ParagraphStyle(
            'Timestamp',
            parent=styles['Normal'],
            fontName='Courier',
            fontSize=8,
            textColor=ACCENT_OLIVE,
            spaceAfter=2,
        )

        tip_style = ParagraphStyle(
            'TipBox',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=9,
            leading=13,
            textColor=ACCENT_OLIVE,
            leftIndent=10,
            borderPadding=6,
            spaceAfter=10,
        )

        term_style = ParagraphStyle(
            'TermBold',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=14,
            textColor=TEXT_PRIMARY,
        )

        definition_style = ParagraphStyle(
            'Definition',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=TEXT_SECONDARY,
        )

        quiz_q_style = ParagraphStyle(
            'QuizQuestion',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=14,
            textColor=TEXT_PRIMARY,
            spaceAfter=4,
        )

        quiz_a_style = ParagraphStyle(
            'QuizAnswer',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=9,
            leading=13,
            textColor=ACCENT_OLIVE,
            leftIndent=16,
            spaceAfter=2,
        )

        quiz_explain_style = ParagraphStyle(
            'QuizExplanation',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=13,
            textColor=TEXT_MUTED,
            leftIndent=16,
            spaceAfter=10,
        )

        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8,
            textColor=TEXT_MUTED,
            alignment=TA_CENTER,
            spaceBefore=20,
        )

        elements = []

        # ── Title Block ──
        elements.append(Paragraph(title, title_style))
        elements.append(Paragraph("Clipnote AI &bull; Lecture Notes &amp; Study Material", subtitle_style))
        elements.append(HRFlowable(
            width="100%", thickness=2, color=ACCENT_OLIVE,
            spaceAfter=20, spaceBefore=0
        ))

        # ── Study Guide Section ──
        if structured_content.get("study_guide"):
            elements.append(cls._section_banner("EXECUTIVE STUDY GUIDE", "01"))
            guide_lines = structured_content["study_guide"].split("\n")
            for line in guide_lines:
                if line.strip():
                    clean_line = line.replace("#", "").replace("*", "").strip()
                    if clean_line.startswith("- ") or clean_line.startswith("* "):
                        elements.append(Paragraph(f"&#8226; {clean_line[2:]}", bullet_style))
                    else:
                        elements.append(Paragraph(clean_line, body_style))
            elements.append(Spacer(1, 14))

        # ── Sectioned Notes ──
        notes = structured_content.get("notes", [])
        if notes:
            elements.append(cls._section_banner("SECTIONED NOTES", "02"))
            for i, item in enumerate(notes):
                sec_title = item.get("section_title", "Section")
                content = item.get("content", "")
                ts = item.get("timestamp_reference", 0.0)
                minutes = int(ts // 60)
                seconds = int(ts % 60)
                ts_str = f"[{minutes:02d}:{seconds:02d}]"

                elements.append(Paragraph(f"{sec_title}", subsection_style))
                elements.append(Paragraph(ts_str, timestamp_style))

                for line in content.split("\n"):
                    if line.strip():
                        clean = line.strip()
                        if clean.startswith("- ") or clean.startswith("* "):
                            elements.append(Paragraph(f"&#8226; {clean[2:]}", bullet_style))
                        else:
                            elements.append(Paragraph(clean, body_style))
                elements.append(Spacer(1, 6))
            elements.append(Spacer(1, 10))

        # ── Key Concepts Glossary Table ──
        concepts = structured_content.get("key_concepts", [])
        if concepts:
            elements.append(cls._section_banner("KEY CONCEPTS GLOSSARY", "03"))

            table_data = [
                [Paragraph("<b>Term</b>", term_style), 
                 Paragraph("<b>Definition</b>", definition_style)]
            ]
            for c in concepts:
                table_data.append([
                    Paragraph(c.get("term", ""), term_style),
                    Paragraph(c.get("definition", ""), definition_style)
                ])

            t = Table(table_data, colWidths=[140, 380])
            t.setStyle(TableStyle([
                # Header row
                ('BACKGROUND', (0, 0), (-1, 0), SECTION_BG),
                ('TEXTCOLOR', (0, 0), (-1, 0), TEXT_PRIMARY),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                # Body
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('LEFTPADDING', (0, 0), (-1, -1), 10),
                ('RIGHTPADDING', (0, 0), (-1, -1), 10),
                # Borders
                ('LINEBELOW', (0, 0), (-1, 0), 1.5, ACCENT_OLIVE),
                ('LINEBELOW', (0, 1), (-1, -1), 0.5, BORDER_WARM),
                # Alternating row backgrounds
                *[('BACKGROUND', (0, i), (-1, i), CREAM_BG) for i in range(2, len(table_data), 2)],
            ]))
            elements.append(t)
            elements.append(Spacer(1, 14))

        # ── Quiz Section ──
        quiz = structured_content.get("quiz", [])
        if quiz:
            elements.append(cls._section_banner("SELF-ASSESSMENT QUIZ", "04"))

            for i, q in enumerate(quiz, 1):
                question_text = q.get("question", "")
                elements.append(Paragraph(
                    f"<b>Q{i}.</b> {question_text}", quiz_q_style
                ))

                if q.get("type") == "mcq" and q.get("options"):
                    option_letters = ["A", "B", "C", "D", "E", "F"]
                    for j, opt in enumerate(q["options"]):
                        letter_label = option_letters[j] if j < len(option_letters) else str(j+1)
                        elements.append(Paragraph(
                            f"({letter_label}) {opt}", bullet_style
                        ))

                elements.append(Paragraph(
                    f"Answer: {q.get('correct_answer', '')}", quiz_a_style
                ))
                if q.get("explanation"):
                    elements.append(Paragraph(
                        f"Explanation: {q['explanation']}", quiz_explain_style
                    ))
                elements.append(Spacer(1, 6))

        # ── Footer ──
        elements.append(HRFlowable(
            width="100%", thickness=1, color=BORDER_WARM,
            spaceAfter=10, spaceBefore=20
        ))
        elements.append(Paragraph(
            "Generated by Clipnote AI Lecture Note Taker &bull; clipnote.app",
            footer_style
        ))

        doc.build(elements)
        return output_path

    @classmethod
    def _section_banner(cls, title: str, number: str):
        """Creates a styled section banner with number badge and title, matching reference editorial style."""
        styles = getSampleStyleSheet()
        
        banner_data = [[
            Paragraph(
                f'<font color="#FFFFFF"><b>{number}</b></font>', 
                ParagraphStyle('BannerNum', parent=styles['Normal'], 
                    fontName='Helvetica-Bold', fontSize=11, alignment=TA_CENTER, 
                    textColor=colors.white, leading=14)
            ),
            Paragraph(
                f'<font color="#2C2316"><b>{title}</b></font>',
                ParagraphStyle('BannerTitle', parent=styles['Normal'],
                    fontName='Helvetica-Bold', fontSize=11, 
                    textColor=TEXT_PRIMARY, leading=14,
                    spaceBefore=0, spaceAfter=0)
            )
        ]]
        
        t = Table(banner_data, colWidths=[36, 484])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, 0), ACCENT_OLIVE),
            ('BACKGROUND', (1, 0), (1, 0), SECTION_BG),
            ('ALIGN', (0, 0), (0, 0), 'CENTER'),
            ('ALIGN', (1, 0), (1, 0), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (0, 0), 6),
            ('LEFTPADDING', (1, 0), (1, 0), 12),
            ('ROUNDEDCORNERS', [4, 4, 4, 4]),
            ('BOX', (0, 0), (-1, -1), 0.5, BORDER_WARM),
        ]))
        
        return KeepTogether([Spacer(1, 12), t, Spacer(1, 10)])

    @classmethod
    def export_anki(cls, structured_content: Dict[str, Any]) -> str:
        """Generates Anki-compatible TSV flashcard format (Front \\t Back)."""
        lines = ["#separator:tab", "#html:true", "#tags:clipnote lecture"]
        concepts = structured_content.get("key_concepts", [])
        for c in concepts:
            term = c.get("term", "").replace("\t", " ")
            definition = c.get("definition", "").replace("\t", " ")
            lines.append(f"{term}\t{definition}")
        
        quiz = structured_content.get("quiz", [])
        for q in quiz:
            question = q.get("question", "").replace("\t", " ")
            ans = q.get("correct_answer", "").replace("\t", " ")
            if q.get("explanation"):
                ans += f"<br><i>{q['explanation']}</i>"
            lines.append(f"{question}\t{ans}")

        return "\n".join(lines)
