import os
from pathlib import Path
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from config import settings

class IExporterService:
    """Service interface for exporting notes, quizzes, study guides into PDF, Markdown, and Anki formats."""

    @classmethod
    def export_markdown(cls, title: str, structured_content: Dict[str, Any], include_quiz: bool = True) -> str:
        """Generates clean Markdown representation of the lecture notes and study guide."""
        md = []
        md.append(f"# {title}\n")
        md.append(f"*Generated by Clipnote AI Lecture Note Taker*\n\n")

        # Study Guide
        if structured_content.get("study_guide"):
            md.append("## 📌 Executive Study Guide\n")
            md.append(f"{structured_content['study_guide']}\n\n")

        # Notes
        notes = structured_content.get("notes", [])
        if notes:
            md.append("## 📝 Sectioned Notes\n")
            for item in notes:
                ts = item.get("timestamp_reference", 0.0)
                minutes = int(ts // 60)
                seconds = int(ts % 60)
                ts_str = f"{minutes:02d}:{seconds:02d}"
                md.append(f"### {item.get('section_title', 'Section')} `[{ts_str}]`\n")
                md.append(f"{item.get('content', '')}\n\n")

        # Key Concepts
        concepts = structured_content.get("key_concepts", [])
        if concepts:
            md.append("## 💡 Key Concepts & Glossary\n")
            for concept in concepts:
                term = concept.get("term", "")
                definition = concept.get("definition", "")
                md.append(f"- **{term}**: {definition}\n")
            md.append("\n")

        # Quiz
        if include_quiz:
            quiz = structured_content.get("quiz", [])
            if quiz:
                md.append("## 🧠 Self-Assessment Quiz\n")
                for i, q in enumerate(quiz, 1):
                    md.append(f"#### Question {i}: {q.get('question', '')}\n")
                    if q.get("type") == "mcq" and q.get("options"):
                        for opt in q["options"]:
                            md.append(f"- [ ] {opt}\n")
                    md.append(f"\n> **Answer**: {q.get('correct_answer', '')}\n")
                    if q.get("explanation"):
                        md.append(f"> *Explanation*: {q['explanation']}\n")
                    md.append("\n")

        return "".join(md)

    @classmethod
    def export_pdf(cls, title: str, structured_content: Dict[str, Any], output_path: Path) -> Path:
        """Generates a styled PDF document using ReportLab."""
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=letter,
            rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40
        )
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#0F172A'),
            spaceAfter=6
        )
        subtitle_style = ParagraphStyle(
            'DocSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=10,
            textColor=colors.HexColor('#64748B'),
            spaceAfter=15
        )
        h2_style = ParagraphStyle(
            'Heading2Custom',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#1E293B'),
            spaceBefore=12,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            'BodyCustom',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#334155'),
            spaceAfter=8
        )

        elements = []
        elements.append(Paragraph(title, title_style))
        elements.append(Paragraph("Clipnote AI Generated Lecture Summary & Notes", subtitle_style))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#E2E8F0'), spaceAfter=15))

        # Study Guide
        if structured_content.get("study_guide"):
            elements.append(Paragraph("Executive Study Guide", h2_style))
            guide_lines = structured_content["study_guide"].split("\n")
            for line in guide_lines:
                if line.strip():
                    clean_line = line.replace("#", "").replace("*", "").strip()
                    elements.append(Paragraph(clean_line, body_style))
            elements.append(Spacer(1, 10))

        # Notes
        notes = structured_content.get("notes", [])
        if notes:
            elements.append(Paragraph("Sectioned Notes", h2_style))
            for item in notes:
                sec_title = item.get("section_title", "Section")
                content = item.get("content", "")
                elements.append(Paragraph(f"<b>{sec_title}</b>", body_style))
                elements.append(Paragraph(content, body_style))
                elements.append(Spacer(1, 4))
            elements.append(Spacer(1, 10))

        # Key Concepts Table
        concepts = structured_content.get("key_concepts", [])
        if concepts:
            elements.append(Paragraph("Key Concepts Glossary", h2_style))
            table_data = [["Term", "Definition"]]
            for c in concepts:
                table_data.append([c.get("term", ""), c.get("definition", "")])

            t = Table(table_data, colWidths=[150, 380])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ]))
            elements.append(t)

        doc.build(elements)
        return output_path

    @classmethod
    def export_anki(cls, structured_content: Dict[str, Any]) -> str:
        """Generates Anki-compatible TSV flashcard format (Front \\t Back)."""
        lines = ["#separator:tab", "#html:true", "#tags:clipnote lecture"]
        concepts = structured_content.get("key_concepts", [])
        for c in concepts:
            term = c.get("term", "").replace("\t", " ")
            definition = c.get("definition", "").replace("\t", " ")
            lines.append(f"{term}\t{definition}")
        
        quiz = structured_content.get("quiz", [])
        for q in quiz:
            question = q.get("question", "").replace("\t", " ")
            ans = q.get("correct_answer", "").replace("\t", " ")
            if q.get("explanation"):
                ans += f"<br><i>{q['explanation']}</i>"
            lines.append(f"{question}\t{ans}")

        return "\n".join(lines)
